// Location data utilities for countries, states, and postal codes

export interface Country {
  name: string;
  code: string;
  phoneCode: string;
}

export interface State {
  name: string;
  code: string;
}

export const countries: Country[] = [
  { name: 'United States', code: 'US', phoneCode: '+1' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44' },
  { name: 'Canada', code: 'CA', phoneCode: '+1' },
  { name: 'Australia', code: 'AU', phoneCode: '+61' },
  { name: 'Germany', code: 'DE', phoneCode: '+49' },
  { name: 'France', code: 'FR', phoneCode: '+33' },
  { name: 'Italy', code: 'IT', phoneCode: '+39' },
  { name: 'Spain', code: 'ES', phoneCode: '+34' },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31' },
  { name: 'Belgium', code: 'BE', phoneCode: '+32' },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41' },
  { name: 'Austria', code: 'AT', phoneCode: '+43' },
  { name: 'Sweden', code: 'SE', phoneCode: '+46' },
  { name: 'Norway', code: 'NO', phoneCode: '+47' },
  { name: 'Denmark', code: 'DK', phoneCode: '+45' },
  { name: 'Finland', code: 'FI', phoneCode: '+358' },
  { name: 'Ireland', code: 'IE', phoneCode: '+353' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351' },
  { name: 'Greece', code: 'GR', phoneCode: '+30' },
  { name: 'Poland', code: 'PL', phoneCode: '+48' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420' },
  { name: 'Hungary', code: 'HU', phoneCode: '+36' },
  { name: 'Slovakia', code: 'SK', phoneCode: '+421' },
  { name: 'Slovenia', code: 'SI', phoneCode: '+386' },
  { name: 'Croatia', code: 'HR', phoneCode: '+385' },
  { name: 'Bosnia and Herzegovina', code: 'BA', phoneCode: '+387' },
  { name: 'Serbia', code: 'RS', phoneCode: '+381' },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382' },
  { name: 'North Macedonia', code: 'MK', phoneCode: '+389' },
  { name: 'Albania', code: 'AL', phoneCode: '+355' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359' },
  { name: 'Romania', code: 'RO', phoneCode: '+40' },
  { name: 'Moldova', code: 'MD', phoneCode: '+373' },
  { name: 'Ukraine', code: 'UA', phoneCode: '+380' },
  { name: 'Belarus', code: 'BY', phoneCode: '+375' },
  { name: 'Lithuania', code: 'LT', phoneCode: '+370' },
  { name: 'Latvia', code: 'LV', phoneCode: '+371' },
  { name: 'Estonia', code: 'EE', phoneCode: '+372' },
  { name: 'India', code: 'IN', phoneCode: '+91' },
  { name: 'China', code: 'CN', phoneCode: '+86' },
  { name: 'Japan', code: 'JP', phoneCode: '+81' },
  { name: 'South Korea', code: 'KR', phoneCode: '+82' },
  { name: 'Singapore', code: 'SG', phoneCode: '+65' },
  { name: 'Malaysia', code: 'MY', phoneCode: '+60' },
  { name: 'Thailand', code: 'TH', phoneCode: '+66' },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62' },
  { name: 'Philippines', code: 'PH', phoneCode: '+63' },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84' },
  { name: 'Brazil', code: 'BR', phoneCode: '+55' },
  { name: 'Mexico', code: 'MX', phoneCode: '+52' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Chile', code: 'CL', phoneCode: '+56' },
  { name: 'Colombia', code: 'CO', phoneCode: '+57' },
  { name: 'Peru', code: 'PE', phoneCode: '+51' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58' },
  { name: 'Ecuador', code: 'EC', phoneCode: '+593' },
  { name: 'Uruguay', code: 'UY', phoneCode: '+598' },
  { name: 'Paraguay', code: 'PY', phoneCode: '+595' },
  { name: 'Bolivia', code: 'BO', phoneCode: '+591' },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27' },
  { name: 'Egypt', code: 'EG', phoneCode: '+20' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234' },
  { name: 'Kenya', code: 'KE', phoneCode: '+254' },
  { name: 'Ghana', code: 'GH', phoneCode: '+233' },
  { name: 'Morocco', code: 'MA', phoneCode: '+212' },
  { name: 'Tunisia', code: 'TN', phoneCode: '+216' },
  { name: 'Israel', code: 'IL', phoneCode: '+972' },
  { name: 'Turkey', code: 'TR', phoneCode: '+90' },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '+966' },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '+971' },
  { name: 'Qatar', code: 'QA', phoneCode: '+974' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965' },
  { name: 'Bahrain', code: 'BH', phoneCode: '+973' },
  { name: 'Oman', code: 'OM', phoneCode: '+968' },
  { name: 'Jordan', code: 'JO', phoneCode: '+962' },
  { name: 'Lebanon', code: 'LB', phoneCode: '+961' },
  { name: 'Iraq', code: 'IQ', phoneCode: '+964' },
  { name: 'Iran', code: 'IR', phoneCode: '+98' },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94' },
  { name: 'Nepal', code: 'NP', phoneCode: '+977' },
  { name: 'Bhutan', code: 'BT', phoneCode: '+975' },
  { name: 'Maldives', code: 'MV', phoneCode: '+960' },
  { name: 'New Zealand', code: 'NZ', phoneCode: '+64' },
  { name: 'Fiji', code: 'FJ', phoneCode: '+679' },
  { name: 'Papua New Guinea', code: 'PG', phoneCode: '+675' },
  { name: 'Solomon Islands', code: 'SB', phoneCode: '+677' },
  { name: 'Vanuatu', code: 'VU', phoneCode: '+678' },
  { name: 'Samoa', code: 'WS', phoneCode: '+685' },
  { name: 'Tonga', code: 'TO', phoneCode: '+676' },
  { name: 'Kiribati', code: 'KI', phoneCode: '+686' },
  { name: 'Tuvalu', code: 'TV', phoneCode: '+688' },
  { name: 'Nauru', code: 'NR', phoneCode: '+674' },
  { name: 'Marshall Islands', code: 'MH', phoneCode: '+692' },
  { name: 'Micronesia', code: 'FM', phoneCode: '+691' },
  { name: 'Palau', code: 'PW', phoneCode: '+680' },
];

const statesData: Record<string, State[]> = {
  US: [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
  ],
  CA: [
    { name: 'Alberta', code: 'AB' },
    { name: 'British Columbia', code: 'BC' },
    { name: 'Manitoba', code: 'MB' },
    { name: 'New Brunswick', code: 'NB' },
    { name: 'Newfoundland and Labrador', code: 'NL' },
    { name: 'Northwest Territories', code: 'NT' },
    { name: 'Nova Scotia', code: 'NS' },
    { name: 'Nunavut', code: 'NU' },
    { name: 'Ontario', code: 'ON' },
    { name: 'Prince Edward Island', code: 'PE' },
    { name: 'Quebec', code: 'QC' },
    { name: 'Saskatchewan', code: 'SK' },
    { name: 'Yukon', code: 'YT' },
  ],
  AU: [
    { name: 'Australian Capital Territory', code: 'ACT' },
    { name: 'New South Wales', code: 'NSW' },
    { name: 'Northern Territory', code: 'NT' },
    { name: 'Queensland', code: 'QLD' },
    { name: 'South Australia', code: 'SA' },
    { name: 'Tasmania', code: 'TAS' },
    { name: 'Victoria', code: 'VIC' },
    { name: 'Western Australia', code: 'WA' },
  ],
  IN: [
    { name: 'Andhra Pradesh', code: 'AP' },
    { name: 'Arunachal Pradesh', code: 'AR' },
    { name: 'Assam', code: 'AS' },
    { name: 'Bihar', code: 'BR' },
    { name: 'Chhattisgarh', code: 'CG' },
    { name: 'Goa', code: 'GA' },
    { name: 'Gujarat', code: 'GJ' },
    { name: 'Haryana', code: 'HR' },
    { name: 'Himachal Pradesh', code: 'HP' },
    { name: 'Jharkhand', code: 'JH' },
    { name: 'Karnataka', code: 'KA' },
    { name: 'Kerala', code: 'KL' },
    { name: 'Madhya Pradesh', code: 'MP' },
    { name: 'Maharashtra', code: 'MH' },
    { name: 'Manipur', code: 'MN' },
    { name: 'Meghalaya', code: 'ML' },
    { name: 'Mizoram', code: 'MZ' },
    { name: 'Nagaland', code: 'NL' },
    { name: 'Odisha', code: 'OR' },
    { name: 'Punjab', code: 'PB' },
    { name: 'Rajasthan', code: 'RJ' },
    { name: 'Sikkim', code: 'SK' },
    { name: 'Tamil Nadu', code: 'TN' },
    { name: 'Telangana', code: 'TG' },
    { name: 'Tripura', code: 'TR' },
    { name: 'Uttar Pradesh', code: 'UP' },
    { name: 'Uttarakhand', code: 'UK' },
    { name: 'West Bengal', code: 'WB' },
    { name: 'Delhi', code: 'DL' },
    { name: 'Jammu and Kashmir', code: 'JK' },
    { name: 'Ladakh', code: 'LA' },
    { name: 'Puducherry', code: 'PY' },
  ],
};

export function getStatesForCountry(countryCode: string): State[] {
  return statesData[countryCode] || [];
}

export function getCountryByName(name: string): Country | undefined {
  return countries.find(country =>
    country.name.toLowerCase() === name.toLowerCase()
  );
}

export function getStateByName(countryCode: string, stateName: string): State | undefined {
  const states = getStatesForCountry(countryCode);
  return states.find(state =>
    state.name.toLowerCase() === stateName.toLowerCase()
  );
}

export function validatePostalCode(countryCode: string, postalCode: string): boolean {
  // Basic validation patterns for different countries
  const patterns: Record<string, RegExp> = {
    US: /^\d{5}(-\d{4})?$/,
    CA: /^[A-Za-z]\d[A-Za-z] ?\d[A-Za-z]\d$/,
    GB: /^[A-Za-z]{1,2}\d[A-Za-z\d]? ?\d[A-Za-z]{2}$/,
    AU: /^\d{4}$/,
    DE: /^\d{5}$/,
    FR: /^\d{5}$/,
    IN: /^\d{6}$/,
    // Add more patterns as needed
  };

  const pattern = patterns[countryCode];
  return pattern ? pattern.test(postalCode) : true; // Default to valid if no pattern
}